server:
  port: 8888
spring:
  datasource:
    username: root
    password: a14725800
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.205.210.108:3306/mytestdb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
logging:
  config:
  classpath: logback.xml
